version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - '8085:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_PORT=3306
    depends_on:
      - mysql


    
# To work with external clients outside of the network you should use this 127.0.0.1 instead "mysql" DNS name 

#The reason it worked with 127.0.0.1 instead of mysql is likely due to how Docker handles networking.
#
#When you use host: 'mysql', you're relying on Docker's internal DNS resolution to translate the hostname 'mysql' to the IP address of your MySQL container. However, sometimes there can be issues with DNS resolution, especially on certain operating systems or network configurations.
#
#By using 127.0.0.1, you're directly specifying the loopback address, which always refers to the local machine. This way, you're bypassing any potential DNS resolution issues that might be occurring in your environment.
#
#It's important to note that this solution will work as long as your MySQL container is running on the same machine as your Node.js application. If you were to deploy your application in a different environment, you might need to adjust the host configuration accordingly.
#
#In production environments, it's common to use environment variables to specify the database host so that the application can be easily configured for different deployment scenarios.

# For example here 